# Site settings
title: repoleved
email: songskysun@example.com
description: 게으른 개발자의 끄적끄적
twitter_username: songskysun
github_username: songskysun

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"