# Setup
title:               repoleved
tagline:             'blog'
description:         '게으른 개발자 끄적끄적'
url:                 https://songskysun.github.io
baseurl:             ''
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Hyesung Shin
  url:               https://github.com/songskysun
  email:             songskysun@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
